### ISSUE TITLE
Can't reload gradle project

### ISSUE THREAD

**Issue by EmptyIrony** [asbyth/ForgeTemplate#2]
dump:
Could not find net.minecraftforge:forgeBin:1.8.9-11.15.1.2318-1.8.9.
Searched in the following locations:
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9/forgeBin-1.8.9-11.15.1.2318-1.8.9.pom
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9/forgeBin-1.8.9-11.15.1.2318-1.8.9.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9/forgeBin-1.8.9-11.15.1.2318-1.8.9.pom
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9/forgeBin-1.8.9-11.15.1.2318-1.8.9.pom
  - file:/C:/Users/EmptyIrony/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9/forgeBin-1.8.9-11.15.1.2318-1.8.9.pom
  - file:/C:/Users/EmptyIrony/.gradle/caches/minecraft/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/stable/22/forgeBin-1.8.9-11.15.1.2318-1.8.9.jar
  - file:/C:/Users/EmptyIrony/.gradle/caches/minecraft/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/stable/22/forgeBin.jar

Is forge server down?

**Comment by EmptyIrony** [comment]
i cleaned cache ,its done

**Comment by VytskaLT** [comment]
Same issue, what cache to I have to clear to fix this?
