### ISSUE TITLE
Could not determine the dependencies of task ':runClient'

### ISSUE THREAD

**Issue by db1218** [asbyth/ForgeTemplate#4]
First off, thanks for creating this.

Using this template, `./gradlew setupDevWorkspace` works fine, but `./gradlew runClient` returns the following error message. I'm still trying to learn gradle, so I'm not sure how to diagnose such an issue.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':runClient'.
> Resolving dependency configuration 'runtimeOnly' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'runtimeOnly' should be resolved.
```

Any ideas?

**Comment by asbyth** [comment]
1: Try changing `id "net.minecraftforge.gradle.forge" version "86b2392"` to `id "net.minecraftforge.gradle.forge" version "6f53277"`
2: Try using the `genIntellijRuns` task and running the generated config instead of `runClient`

**Comment by db1218** [comment]
Ah ha, it was the runClient that was the issue. Ran it in IntelliJ with the generated runs instead of trying to do it with VSCode and it works well, cheers.

**Comment by borodin0v** [comment]
I ran genIntellijRuns and there is no GradleStart class
